version: '3'
services:
  database:
    image: postgres:latest
    restart: always
    env_file:
      - api/.env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
  api:
    build: ./api
    restart: always
    env_file:
      - api/.env
    volumes:
      - ./api:/usr/src/api/
      - /usr/src/api/node_modules
    links:
      - database
    depends_on:
      - database
  nginx:
    restart: always
    build: ./nginx
    ports:
      - '5000:80'
    depends_on:
      - api
      - database
volumes:
  dbdata: